### ISSUE TITLE
osx lion npm install -g sigar fails (local install fails as well)

### ISSUE THREAD

**Issue by ktiedt** [wdavidw/node-sigar#6]
This is on OSX Lion 10.7.2 latest updates

> sigar@0.0.1 preinstall /usr/local/lib/node_modules/sigar
> node-waf clean || (exit 0); node-waf configure build

Nothing to clean (project not configured)
Setting srcdir to                        : /usr/local/lib/node_modules/sigar 
Setting blddir to                        : /usr/local/lib/node_modules/sigar/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node_modules 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.5 
./autogen.sh: running `glibtoolize --copy --force' 
glibtoolize: putting auxiliary files in`.'.
glibtoolize: copying file `./ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIR,`m4'.
glibtoolize: copying file `m4/libtool.m4'
glibtoolize: copying file`m4/ltoptions.m4'
glibtoolize: copying file `m4/ltsugar.m4'
glibtoolize: copying file`m4/ltversion.m4'
glibtoolize: copying file `m4/lt~obsolete.m4'
glibtoolize: Consider adding`-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
./autogen.sh: running `aclocal' 
./autogen.sh: running`automake --add-missing --copy' 
configure.ac:6: installing `./config.sub'
configure.ac:5: installing`./missing'
configure.ac:5: installing `./install-sh'
configure.ac:6: installing`./config.guess'
bindings/lua/Makefile.am: installing `./depcomp'
./autogen.sh: running`autoconf' 
configure.ac:31: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
/usr/local/lib/node_modules/sigar/wscript:18: error: Configuring sigar failed.
npm ERR! error installing sigar@0.0.1 Error: sigar@0.0.1 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! error installing sigar@0.0.1 `sh "-c" "node-waf clean || (exit 0); node-waf configure build"` failed with 1
npm ERR! error installing sigar@0.0.1     at ChildProcess.<anonymous> (/usr/local/Cellar/node/0.6.5/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing sigar@0.0.1     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing sigar@0.0.1     at maybeExit (child_process.js:359:16)
npm ERR! error installing sigar@0.0.1     at Process.onexit (child_process.js:395:5)
npm ERR! sigar@0.0.1 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! `sh "-c" "node-waf clean || (exit 0); node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the sigar@0.0.1 preinstall script.
npm ERR! This is most likely a problem with the sigar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || (exit 0); node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sigar
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "sigar"
npm ERR! cwd /Users/ktiedt
npm ERR! node -v v0.6.5
npm ERR! npm -v 1.1.0-alpha-6
npm ERR! code ELIFECYCLE
npm ERR! message sigar@0.0.1 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! message `sh "-c" "node-waf clean || (exit 0); node-waf configure build"` failed with 1

**Comment by wdavidw** [comment]
Yes, this is a know problem with homebrew (work out of the box with a macport installation). Please refer to "http://www.adaltas.com/projects/node-sigar.html" at the bottom of the page. Basically, 'aclocal' is in '/usr' while 'pkg-config' in is '/usr/local' where is homebrew, so we are just adding a reference to the last one

**Comment by ktiedt** [comment]
ahh Thanks David, I searched the github page for OSX stuff, not the other page (figure install stufff would be int he repo ;))

**Comment by wdavidw** [comment]
yes, i might add it, it sounds wise
