### ISSUE TITLE
NPM Install error

### ISSUE THREAD

**Issue by ysstech** [wdavidw/node-sigar#9]
help!
npm ERR! sigar@0.0.2 preinstall: `node-waf clean || (exit 0); node-waf configure build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sigar@0.0.2 preinstall script 'node-waf clean || (exit 0); node-waf configure build'.
npm ERR! This is most likely a problem with the sigar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || (exit 0); node-waf configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sigar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls sigar
npm ERR! There is likely additional logging output above.

**Comment by wdavidw** [comment]
This package was written and tested against Node.js version 0.7. Things have changed a bit since then. Feel free to look into the compilation and contribute.
